name: pinto
description: The pint° programming language
version: 0.0.2
repository: https://github.com/mateusfccp/pinto

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  analyzer: ^6.8.0
  built_collection: ^5.1.1
  code_builder: ^4.10.0
  chalkdart: ^2.2.1
  dart_style: ^2.3.6
  exitcode: ^1.0.1
  freezed_annotation: ^2.4.4
  meta: ^1.15.0
  path: ^1.9.0
  quiver: ^3.2.1
  recase: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.12
  freezed: ^2.5.7
  lints: ^4.0.0
  test: ^1.25.8

executables:
  pinto:
